/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalNoticeRouteImport } from './routes/legal-notice'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DevSkeletonsRouteImport } from './routes/dev-skeletons'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'

const AuthenticatedVetsLazyRouteImport = createFileRoute(
  '/_authenticated/vets',
)()
const AuthenticatedProfileLazyRouteImport = createFileRoute(
  '/_authenticated/profile',
)()
const AuthenticatedPetsLazyRouteImport = createFileRoute(
  '/_authenticated/pets',
)()

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalNoticeRoute = LegalNoticeRouteImport.update({
  id: '/legal-notice',
  path: '/legal-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DevSkeletonsRoute = DevSkeletonsRouteImport.update({
  id: '/dev-skeletons',
  path: '/dev-skeletons',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVetsLazyRoute = AuthenticatedVetsLazyRouteImport.update({
  id: '/vets',
  path: '/vets',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/vets.lazy').then((d) => d.Route),
)
const AuthenticatedProfileLazyRoute =
  AuthenticatedProfileLazyRouteImport.update({
    id: '/profile',
    path: '/profile',
    getParentRoute: () => AuthenticatedRoute,
  } as any).lazy(() =>
    import('./routes/_authenticated/profile.lazy').then((d) => d.Route),
  )
const AuthenticatedPetsLazyRoute = AuthenticatedPetsLazyRouteImport.update({
  id: '/pets',
  path: '/pets',
  getParentRoute: () => AuthenticatedRoute,
} as any).lazy(() =>
  import('./routes/_authenticated/pets.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dev-skeletons': typeof DevSkeletonsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/pets': typeof AuthenticatedPetsLazyRoute
  '/profile': typeof AuthenticatedProfileLazyRoute
  '/vets': typeof AuthenticatedVetsLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cookies': typeof CookiesRoute
  '/dev-skeletons': typeof DevSkeletonsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/pets': typeof AuthenticatedPetsLazyRoute
  '/profile': typeof AuthenticatedProfileLazyRoute
  '/vets': typeof AuthenticatedVetsLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/dev-skeletons': typeof DevSkeletonsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/legal-notice': typeof LegalNoticeRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authenticated/pets': typeof AuthenticatedPetsLazyRoute
  '/_authenticated/profile': typeof AuthenticatedProfileLazyRoute
  '/_authenticated/vets': typeof AuthenticatedVetsLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cookies'
    | '/dev-skeletons'
    | '/forgot-password'
    | '/legal-notice'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/pets'
    | '/profile'
    | '/vets'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cookies'
    | '/dev-skeletons'
    | '/forgot-password'
    | '/legal-notice'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/pets'
    | '/profile'
    | '/vets'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cookies'
    | '/dev-skeletons'
    | '/forgot-password'
    | '/legal-notice'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/verify-email'
    | '/_authenticated/pets'
    | '/_authenticated/profile'
    | '/_authenticated/vets'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  DevSkeletonsRoute: typeof DevSkeletonsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LegalNoticeRoute: typeof LegalNoticeRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-notice': {
      id: '/legal-notice'
      path: '/legal-notice'
      fullPath: '/legal-notice'
      preLoaderRoute: typeof LegalNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev-skeletons': {
      id: '/dev-skeletons'
      path: '/dev-skeletons'
      fullPath: '/dev-skeletons'
      preLoaderRoute: typeof DevSkeletonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vets': {
      id: '/_authenticated/vets'
      path: '/vets'
      fullPath: '/vets'
      preLoaderRoute: typeof AuthenticatedVetsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pets': {
      id: '/_authenticated/pets'
      path: '/pets'
      fullPath: '/pets'
      preLoaderRoute: typeof AuthenticatedPetsLazyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedPetsLazyRoute: typeof AuthenticatedPetsLazyRoute
  AuthenticatedProfileLazyRoute: typeof AuthenticatedProfileLazyRoute
  AuthenticatedVetsLazyRoute: typeof AuthenticatedVetsLazyRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedPetsLazyRoute: AuthenticatedPetsLazyRoute,
  AuthenticatedProfileLazyRoute: AuthenticatedProfileLazyRoute,
  AuthenticatedVetsLazyRoute: AuthenticatedVetsLazyRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CookiesRoute: CookiesRoute,
  DevSkeletonsRoute: DevSkeletonsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LegalNoticeRoute: LegalNoticeRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
